var items={
playerSpawn:{type:'spawn',scenario:"player"},
teleport_area:{type:'teleport',scenario:"teleport"},
cave_rock1:{type:'solid',scenario:"cave",sprite:"mapSprite"},
cave_rock2:{type:'solid',scenario:"cave",sprite:"mapSprite"},
cave_land:{type:'walk',scenario:"cave",sprite:"mapSprite"},
grass_land:{type:'walk',scenario:"grass",sprite:"mapSprite"},
grass_border1:{type:'solid',scenario:"grass",sprite:"mapSprite"},
grass_border2:{type:'solid',scenario:"grass",sprite:"mapSprite"},
grass_bridge1:{type:'walk',scenario:"grass",sprite:"mapSprite"},
building_chinese1:{type:'solid',scenario:"building",sprite:"mapSprite"},
building_modern1:{type:'solid',scenario:"building",sprite:"mapSprite"},
building_modern2:{type:'solid',scenario:"building",sprite:"mapSprite"},
building_star1:{type:'solid',scenario:"building",sprite:"mapSprite"},
};